WorkItem.Web/Models/ErrorViewModel.cs
namespace WorkItem.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WorkItem.Web/Models/ItemTrabajoDto.cs
namespace WorkItem.Web.Models
{
    public class ItemTrabajoDto
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public bool Completado { get; set; }
        public DateTime FechaEntrega { get; set; }
        public string Relevancia { get; set; } // "Alta" o "Baja"
        public string? UsuarioAsignado { get; set; } = "";
    }
}

WorkItem.Web/Models/RequestDto.cs
using WorkItem.Web.Utility;
using static WorkItem.Web.Utility.SD;

namespace WorkItem.Web.Models
{
    public class RequestDto
    {
        public ApiType ApiType { get; set; } = ApiType.GET;
        public string Url { get; set; }
        public object Data { get; set; }
        public string AccessToken { get; set; }
        public ContentType ContentType { get; set; } = ContentType.Json;
    }
}

WorkItem.Web/Models/ResponseDto.cs
namespace WorkItem.Web.Models
{
    public class ResponseDto
    {
        public object? Result { get; set; }
        public bool IsSuccess { get; set; } = true;
        public string Message { get; set; } = "";
    }
}

WorkItem.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Cors.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Diagnostics;
using WorkItem.Web.Models;
using WorkItem.Web.Service.IService;

namespace WorkItem.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
		private readonly IItemTrabajoService _itemTrabajoService;
	
		public HomeController(ILogger<HomeController> logger, IItemTrabajoService itemTrabajoService)
        {
            _logger = logger;
			_itemTrabajoService = itemTrabajoService;
		}

		public async Task<IActionResult> Index()
		{
			List<ItemTrabajoDto>? list = new();

			ResponseDto? response = await _itemTrabajoService.GetAllItemTrabajoAsync();

			if (response != null && response.IsSuccess)
			{
				list = JsonConvert.DeserializeObject<List<ItemTrabajoDto>>(Convert.ToString(response.Result));
			}
			else
			{
				TempData["error"] = response?.Message;
			}

			return View(list);
		}

		//public Task<IActionResult> ItemTrabajoIndex()
		//{
		//	return View();
		//}

		public async Task<IActionResult> ItemTrabajoCreate()
		{
			return View();
		}

		[HttpPost]
		public async Task<IActionResult> ItemTrabajoCreate(ItemTrabajoDto model)
		{
			if (ModelState.IsValid)
			{
				ResponseDto? response = await _itemTrabajoService.CreateItemTrabajoAsync(model);

				if (response != null && response.IsSuccess)
				{
					TempData["success"] = "Coupon created successfully";
					return RedirectToAction(nameof(Index));
				}
				else
				{
					TempData["error"] = response?.Message;
				}
			}
			return View(model);
		}
		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WorkItem.Web/Controllers/ItemTrabajoController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Reflection;
using WorkItem.Web.Models;
using WorkItem.Web.Service.IService;

namespace WorkItem.Web.Controllers
{
    public class ItemTrabajoController : Controller
    {
                private readonly IItemTrabajoService _itemTrabajoService;
        public ItemTrabajoController(IItemTrabajoService itemTrabajoService)
        {
            _itemTrabajoService = itemTrabajoService;
        }

		//public IActionResult Index()
		//{
		//	return View();
		//}
		public async Task<IActionResult> Index()
        {
            List<ItemTrabajoDto>? list = new();

            ResponseDto? response = await _itemTrabajoService.GetAllItemTrabajoAsync();

            if (response != null && response.IsSuccess)
            {
                list = JsonConvert.DeserializeObject<List<ItemTrabajoDto>>(Convert.ToString(response.Result));
            }
            else
            {
                TempData["error"] = response?.Message;
            }

            return View(list);
        }

        public async Task<IActionResult> ItemTrabajoCreate()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> ItemTrabajoCreate(ItemTrabajoDto model)
        {
            if (ModelState.IsValid)
            {
                ResponseDto? response = await _itemTrabajoService.CreateItemTrabajoAsync(model);

                if (response != null && response.IsSuccess)
                {
                    TempData["success"] = "Item creado satisfactoriamente";
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    TempData["error"] = response?.Message;
                }
            }
            return View(model);
        }


        public async Task<IActionResult> Asignar(int itemTrabajoId)
        {
            ResponseDto? responseA = await _itemTrabajoService.AsignarAsync(itemTrabajoId);

			List<ItemTrabajoDto>? list = new();

			ResponseDto? response = await _itemTrabajoService.GetAllItemTrabajoAsync();

			if (response != null && response.IsSuccess)
			{
				list = JsonConvert.DeserializeObject<List<ItemTrabajoDto>>(Convert.ToString(response.Result));
			}
			else
			{
				TempData["error"] = response?.Message;
			}

			return View(list);
		}

    }

}

WorkItem.Web/Views/Home/Index.cshtml
@* @model IEnumerable<ItemTrabajoDto>

<div class="card shadow border-0 mt-4">
	<div class="card-header bg-secondary bg-gradient ml-0 py-3">
		<div class="row">
			<div class="col-12 text-center">
				<h1 class="text-white">Lista Items Trabajo</h1>
			</div>
		</div>
	</div>
	<div class="card-body p-4">
		<div class="row pb-3">
			<div class="col-6">
			</div>
			<div class="col-6 text-end">
				<a asp-action="ItemTrabajoCreate" class="btn btn-outline-primary"><i class="bi bi-plus-square"></i> Crear Nuevo Item Trabajo</a>

			</div>
		</div>
		<table class="table">
			<thead>
				<tr>
					<th>
						Titulo
					</th>
					<th>
						Relevancia
					</th>
					<th>
						Fecha Entrega
					</th>
					<th>
						Completado
					</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				@foreach (var item in Model)
				{
					<tr>
						<td>
							@item.Titulo
						</td>
						<td>
							@item.Relevancia
						</td>
						<td>
							@item.FechaEntrega
						</td>
						<td>
							@item.Completado
						</td>
						<td>
							<a asp-action="ItemTrabajoIndex" asp-route-itemTrabajoId="@item.Id" class="btn btn-danger">
								<i class="bi bi-trash">Asignar</i>
							</a>
						</td>
					</tr>
				}
			</tbody>
		</table>
	</div>

</div> *@

WorkItem.Web/Views/ItemTrabajo/Asignar.cshtml
@model IEnumerable<ItemTrabajoDto>

<div class="card shadow border-0 mt-4">
	<div class="card-header bg-secondary bg-gradient ml-0 py-3">
		<div class="row">
			<div class="col-12 text-center">
				<h1 class="text-white">Lista Items Trabajo</h1>
			</div>
		</div>
	</div>
	<div class="card-body p-4">
		<div class="row pb-3">
			<div class="col-6">
			</div>
			<div class="col-6 text-end">
				<a asp-action="ItemTrabajoCreate" class="btn btn-outline-primary"><i class="bi bi-plus-square"></i> Crear Nuevo Item Trabajo</a>

			</div>
		</div>
		<table class="table">
			<thead>
				<tr>
					<th>
						Titulo
					</th>
					<th>
						Relevancia
					</th>
					<th>
						Fecha Entrega
					</th>
					<th>
						Completado
					</th>
					<th>
						Asignado a
					</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				@foreach (var item in Model)
				{
					<tr>
						<td>
							@item.Titulo
						</td>
						<td>
							@item.Relevancia
						</td>
						<td>
							@item.FechaEntrega
						</td>
						<td>
							@item.Completado
						</td>
						<td>
							@item.UsuarioAsignado
						</td>
						<td>
							@if (item.UsuarioAsignado == "")  // Solo si el usuario asignado es "Juan"
							{
								<a asp-action="Asignar" asp-route-itemTrabajoId="@item.Id" class="btn btn-danger">
									<i class="bi bi-trash">Asignar</i>
								</a>
							}
						</td>
					</tr>
				}
			</tbody>
		</table>
	</div>

</div>

WorkItem.Web/Views/ItemTrabajo/Index.cshtml
@model IEnumerable<ItemTrabajoDto>

<div class="card shadow border-0 mt-4">
	<div class="card-header bg-secondary bg-gradient ml-0 py-3">
		<div class="row">
			<div class="col-12 text-center">
				<h1 class="text-white">Lista Items Trabajo</h1>
			</div>
		</div>
	</div>
	<div class="card-body p-4">
		<div class="row pb-3">
			<div class="col-6">
			</div>
			<div class="col-6 text-end">
				<a asp-action="ItemTrabajoCreate" class="btn btn-outline-primary"><i class="bi bi-plus-square"></i> Crear Nuevo Item Trabajo</a>

			</div>
		</div>
		<table class="table">
			<thead>
				<tr>
					<th>
						Titulo
					</th>
					<th>
						Relevancia
					</th>
					<th>
						Fecha Entrega
					</th>
					<th>
						Completado
					</th>
					<th>
						Asignado a
					</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				@foreach (var item in Model)
				{
					<tr>
						<td>
							@item.Titulo
						</td>
						<td>
							@item.Relevancia
						</td>
						<td>
							@item.FechaEntrega
						</td>
						<td>
							@item.Completado
						</td>
						<td>
							@item.UsuarioAsignado
						</td>
						<td>
							@if (item.UsuarioAsignado == "")  // Solo si el usuario asignado es "Juan"
							{
							<a asp-action="Asignar" asp-route-itemTrabajoId="@item.Id" class="btn btn-danger">
								<i class="bi bi-trash">Asignar</i>
							</a>
							}	
						</td>
					</tr>
				}
			</tbody>
		</table>
	</div>

</div>

WorkItem.Web/Views/ItemTrabajo/ItemTrabajoCreate.cshtml
@model ItemTrabajoDto

<form asp-action="ItemTrabajoCreate">
    <br />
    <div class="container border p-3">
        <h1 class="text-white text-center">Crear Item Trabajo</h1>

        <hr />
        <div class="row">
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;"> Titulo</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">Descripcion</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">Fecha Entrega</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="FechaEntrega" class="form-control" />
                <span asp-validation-for="FechaEntrega" class="text-danger"></span>
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">Relevancia</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Relevancia" class="form-control" />
                <span asp-validation-for="Relevancia" class="text-danger"></span>
            </div>
            <div class="col-5 offset-2">

                <a asp-action="Index" class="btn-primary btn form-control ">Atras</a>
            </div>
            <div class="col-5">
                <input type="submit" value="Crear" class="btn btn-success form-control" />
            </div>

        </div>

        <div>
        </div>
    </div>
</form>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

WorkItem.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WorkItem.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WorkItem.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WorkItem.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ItemTrabajo" asp-action="Index">Item Trabajo</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - WorkItem.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>